package com.ptopalidis.cecloud.platform.common.config.resourceserver;

public interface ResourceServerExpressionInterceptUrlRegistryPostProcessor extends ExpressionInterceptUrlRegistryPostProcessor {
}